### ISSUE TITLE
required rust version?

### ISSUE THREAD

**Issue by tisonkun** [DataDog/glommio#516]
Or you can add a [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file.

Failed to compile with "rustc 1.53.0 (53cb7b09b 2021-06-17)":

```
error[E0658]: use of unstable library feature 'maybe_uninit_extra'
    --> glommio/src/executor/mod.rs:2490:82
     |
2490 |         let f_inner = enclose::enclose!((result) move || {result.lock().unwrap().write(func());});
     |                                                                                  ^^^^^
     |
     = note: see issue #63567 <https://github.com/rust-lang/rust/issues/63567> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `glommio`

To learn more, run the command again with --verbose.
```

**Comment by HippoBaro** [comment]
We currently are using 1.58. So far we have tried to stay in sync with stable.

**Comment by glommer** [comment]
going forward we should have a minimum version and stick to it.
We'd like to use GATs soon, so now that they landed maybe it's time to solidify that.

**Comment by tisonkun** [comment]
Thanks for your information! I can compile with 1.58.

Leave it as open util you guys add a section on README.md or a rust-toolchain.toml file.
